### ISSUE TITLE
"Find all" button

### ISSUE THREAD

**Issue by rocketinventor** [c9/c9.ide.find.replace#1]
Most code editors (and text editors for that matter) have the ability to find, and select/highlight all matches inside the document. That feature does not seem to be present inside of the C9 IDE.

**Comment by nightwing** [comment]
Ctl-alt-k (Ctl-alt-G on mac) finds and selects all matches.
And find in files (ctrl-shift-f) has option to find in current file.

**Comment by rocketinventor** [comment]
@nightwing yah, I figured that out now, thanks.
At first I thought it wasn't working because the shortcut listed in the source code wasn't working.
